### ISSUE TITLE
How can actions been passed from a root reducer through to a child reducer?

### ISSUE THREAD

**Issue by james-rantmedia** [johnpatrickmorgan/TCACoordinators#22]
I'm facing an issue where I have an action that I wish to pass from a root reducer all the way through a chain of coordinators to a child reducer...

I have an `AppReducer` which is the entry point of my app. I wish to send `.initialise` to this reducer, and feed it through to an `OnboardingReducer` which exists nested inside some coordinators, and the OnboardingReducer should act on receiving `.initialise` and do some work.

The pseudo-structure is like this

```
AppReducer
    AppCoordinatorReducer
        OnboardingCoordinatorReducer
            OnboardingReducer
```

My `AppView` displays the `AppCoordinatorView`, and on appearance, sends `.initialise` to the `viewStore`, like so:

```swift
public var body: some View {
	WithViewStore(store) { viewStore in
		AppCoordinatorView(
			store: store.scope(
				state: \.appCoordinatorState,
				action: AppAction.appCoordinator
			)
		).onAppear {
			viewStore.send(.initialise)
		}
	}
}
```

What is the proper method to pass that `.initialise` action though the app coordinator, through the onboarding coordinator to end up at its destination: `OnboardingReducer`?

I tried the following, and it worked -- however, I don't think this is the correct approach, and I don't even fully understand *why* it worked... It seems fragile, relying on knowing the index of each coordinator's screen, etc...

This is in my `AppReducer`:
```swift
case .initialise:
	return Effect(
		value: .appCoordinator(
			.routeAction(
				0,
				action: AppScreenAction.onboardingCoordinator(
					OnboardingCoordinatorAction.routeAction(
						0,
						action: OnboardingScreenAction.welcome(
							OnboardingAction.initialise
						)
					)
				)
			)
		)
	)
```

**Comment by johnpatrickmorgan** [comment]
Hi @james-rantmedia, thanks for raising this issue. Admittedly, it's a bit awkward to pass actions through to a child reducer, especially a 'grandchild' reducer in this case. That stems from the flexibility the routes array allows: the app coordinator's routes might not include an onboarding coordinator at all, or they might include several onboarding coordinators, so the particular onboarding coordinator to which the action should be sent needs to be identified somehow (in this case via an index). The same is true of the welcome screen within the onboarding coordinator's routes: there could be zero or more welcome screens within the routes array, so sending an action to the correct one requires identifying it via its index. 

You might prefer to find the index at runtime rather than hardcoding it. If you only expect there to be one onboarding coordinator, you could find the first matching index within the routes array, and then dispatch an action to that index. I'd be inclined to add an `initialise` case to the `OnboardingCoordinatorAction` enum, so that the action can be passed down in two steps, the first of which would look something like:

```swift 
case .initialise:
  if let index = state.appCoordinator.routes.firstIndex(where: { /AppScreen.onboardingCoordinator ~= $0.screen }) {
    return Effect(value: .appCoordinator(.routeAction(index, action: .onboardingCoordinator(.initialise)))
  }
```

And then the onboarding coordinator could do something similar to pass the action down one step further to the welcome screen.

**Comment by james-rantmedia** [comment]
Thanks for the reply, the explanation makes sense to me now. You're right, it does feel a bit awkward. Is this just something we'll have to live with due to the way TCACoordinators work or could it be improved in the future?

**Comment by johnpatrickmorgan** [comment]
I think it's always going to be slightly tricky as the code has to handle cases where there are zero or multiple children of the intended type. It might be worth considering whether the app coordinator needs a routes array though - e.g. if it only ever shows one child coordinator at a time, it might simplify things to conditionally show the relevant coordinator, perhaps with a transition between them, instead of using TCACoordinators, e.g. how this [example app coordinator](https://github.com/johnpatrickmorgan/TCACoordinators/blob/2461e380bdd50da93cf64375e059c79438c90749/TCACoordinatorsExample/TCACoordinatorsExample/Game/AppCoordinator.swift) switches between a logged in and logged out coordinator.

**Comment by james-rantmedia** [comment]
Yeah, that's a good idea, I can probably do that. Thanks!
