### ISSUE TITLE
Data Flow through TCACoordinators?

### ISSUE THREAD

**Issue by rhysm94** [johnpatrickmorgan/TCACoordinators#30]
I'm having some issues coming up with a way to send data from my nested views back to my Coordinator state, when building a multi-step form.

I've created a repository with a [sample SwiftPM application](https://github.com/rhysm94/TCA-Coordinator-Form), with a three step form, and a submission page. Currently, they don't have any means of communication with each other.

In this example codebase, I'd like to be able to persist the values in Step 1, Step 2, and Step 3, so that the user can go back and forth between each page without losing any data, but I can't find any hook for when the current page state is updated. The `updateRoutes` action doesn't get called when I'd expect it to, only seemingly when the view is dismissed, not presented on top of.

Is there something I'm missing with this? It feels like I should be able to keep Step 1, 2, and 3 state in my Coordinator state (or even a parent state), so that next time the user navigates from Step 1 -> Step 2, I can call:

```swift
state.routes.push(.step2(state.step2State))
```
and have that view pre-populated with whatever was entered from when they were last on the Step 2 page.

Any help here would be massively appreciated! Thanks!

**Comment by johnpatrickmorgan** [comment]
Hi @rhysm94! Thanks for raising this issue, and for the example code. I've imported your code into the example project and adapted it in [this commit](https://github.com/johnpatrickmorgan/TCACoordinators/commit/81630a029e62818b8823d0a0cc07bf8e9359785f#diff-79f4fecc082ca20482c848f72718d83daea55477df89850931adb4c0304873d8). Essentially, I've added state to the coordinator for each of the steps as you said. With the state held in the coordinator, the stored routes no longer need to store data, just a screen identifier - `IdentifiedArrayOf<Route<AppFlowState.ID>>`. But in order to hook up to the router, a `IdentifiedArrayOf<Route<AppFlowState>>` computed variable is used. With that, you can just push an ID to push a new screen, `state.routes.push(.step2(state.step2State))`. The important changes I made are in the [FormAppCoordinator.swift](https://github.com/johnpatrickmorgan/TCACoordinators/blob/81630a029e62818b8823d0a0cc07bf8e9359785f/TCACoordinatorsExample/TCACoordinatorsExample/Form/FormAppCoordinator.swift). There might be other approaches but I think that way works well. Hope that helps.

**Comment by rhysm94** [comment]
Thank you very much! That worked perfectly.

I did hit a snag at one point, on the actual project this is for, which involves a few more screens. For some reason, it was compiling just fine, but I was hitting an `EXC_BAD_ACCESS code=1` crash in a `WithViewStore` initialiser, on the `removeDuplicates: ==` argument, as soon as I was trying to launch the coordinator. Not entirely sure why, or how it was happening, but after retrying a few times and probably fiddling with the code, it just worked 🤷🏻‍♂️

Anyway, thanks again - this has been an enormous help!

**Comment by johnpatrickmorgan** [comment]
Great, glad it helped! I might adapt this demo to include in the example app if that's ok?

**Comment by rhysm94** [comment]
Yes, absolutely! More than happy 😃
