### ISSUE TITLE
Support Custom transition

### ISSUE THREAD

**Issue by toanbv-fabbi** [johnpatrickmorgan/TCACoordinators#48]
Hi guy
I want to make custom transition "flipHorizontal" like UIKit:
guard let vc = storyboard?.instantiateViewController(identifier: "SecondViewController") else { return }
vc.modalTransitionStyle = .flipHorizontal
vc.modalPresentationStyle = .currentContext
show(vc, sender: self)
How can I make that transition with your library?

**Comment by johnpatrickmorgan** [comment]
Hi @toanbv-fabbi, thanks for raising this issue. I'm afraid this library does not offer a solution for that, because SwiftUI does not currently provide a way to customise the modal transition when presenting a sheet or a full-screen cover. To achieve a custom transition you might want to explore showing the view manually instead (e.g. see https://blog.devgenius.io/swiftui-different-ways-to-present-modal-views-26472947a800), but that's outside this library's scope.

**Comment by toanbv-fabbi** [comment]
@johnpatrickmorgan We can use UIKit to customise the modal transition. 
You can check this library
`class MyViewCoordinator: UIViewControllerCoordinator<MyRoute> {
    override func transition(for route: MyRoute) -> ViewTransition {
        switch route {
            case .foo:
                return .present(Text("Foo"))
            case .bar:
                return .custom {
                    guard let rootViewController = self.rootViewController else {
                        return assertionFailure()
                    }

                    // Use `rootViewController` to perform a custom transition.
                    rootViewController.present(
                        UIViewController(),
                        animated: true,
                        completion: { }
                    )
                }
        }
    }
}`
https://github.com/SwiftUIX/Coordinator
