### ISSUE TITLE
Deprecated scope(state:action:) in TCA 1.6

### ISSUE THREAD

**Issue by tesum** [johnpatrickmorgan/TCACoordinators#63]
Hello, my team write project on TCA 1.6 + TCACoordinators and we encountered a problem in the console: 
`<decode: bad range for [%@] got [offs:410 len:801 within:0]>`

It occurs because of the deprecated method in the `TCARouter.swift:26`. Can you please correct it?

**Comment by sdkdimon** [comment]
I have also try to fix that warning but without no luck ((

**Comment by sdkdimon** [comment]
Have a dirty fix for the issue.
https://github.com/sdkdimon/TCACoordinators/tree/sdkdimon/experimental-tca-190
I suppose to have something cleaner needs to do a whole lib refactor, unfortunately.
That's because deprecated and actual scope methods have a different params, in deprecated one we have closures and in new one there `KeyPath` for state and `CaseKeyPath`  for an action params that can't be created in runtime(

**Comment by johnpatrickmorgan** [comment]
I believe this issue is now resolved since @rhysm94's changes in version [0.9.0](https://github.com/johnpatrickmorgan/TCACoordinators/releases/tag/0.9.0).
